# Generated by Django 6.1 on 2026-08-19 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('function', '関数型'), ('cli', '対話型CLI'), ('plot', 'Matplotlibグラフ')], default='function', max_length=20)),
                ('level', models.IntegerField(choices=[(1, 'レベル1: 基礎・入門'), (2, 'レベル2: 基礎制御・リスト'), (3, 'レベル3: 関数・応用データ構造・標準ライブラリ'), (4, 'レベル4: 実践可視化・アルゴリズム・設計')], default=1)),
                ('category', models.CharField(choices=[('basic', '基本文法・型・計算'), ('control', '制御構文・ループ・条件分岐'), ('data_structure', 'リスト・辞書・データ構造'), ('library', '実用標準ライブラリ (datetime, math, re等)'), ('plot', 'データ可視化 (Matplotlib)'), ('algorithm', 'アルゴリズム・クラス設計')], default='basic', max_length=30)),
                ('order', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='HTML形式の問題文')),
                ('template', models.TextField(help_text='出題用スターターコード')),
                ('test_cases', models.JSONField(default=list, help_text='テストケース配列')),
                ('setup_code', models.TextField(blank=True, default='', help_text='テスト前実行コード')),
                ('hint_1', models.TextField(blank=True, default='', help_text='方針・考え方のヒント (1段階目)')),
                ('hint_2', models.TextField(blank=True, default='', help_text='具体的な関数・文法のヒント (2段階目)')),
                ('model_answer', models.TextField(blank=True, default='', help_text='模範解答コード')),
                ('model_answer_explanation', models.TextField(blank=True, default='', help_text='模範解答の丁寧な解説')),
                ('weight', models.IntegerField(default=10, help_text='基本配点')),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_identifier', models.CharField(default='anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_score', models.FloatField(default=0.0, help_text='総合スコア (0-100)')),
                ('self_reliance_score', models.FloatField(default=100.0, help_text='自力解決力スコア (0-100%)')),
                ('category_scores', models.JSONField(default=dict, help_text='カテゴリ別習熟度スコア {category: score}')),
                ('recommended_chapter', models.IntegerField(default=1, help_text='推奨学習開始章 (1-8)')),
                ('ai_feedback', models.TextField(blank=True, default='', help_text='AIによる診断総評・弱点アドバイス')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False)),
                ('hint_count', models.IntegerField(default=0, help_text='ヒント閲覧回数 (0, 1, 2)')),
                ('model_answer_viewed', models.BooleanField(default=False, help_text='模範解答を閲覧したか')),
                ('attempt_count', models.IntegerField(default=0, help_text='テスト実行試行回数')),
                ('duration_seconds', models.IntegerField(default=0, help_text='解答所要時間(秒)')),
                ('user_code', models.TextField(blank=True, default='')),
                ('earned_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentproblem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'problem')},
            },
        ),
    ]
