# Generated by Django 6.1 on 2026-08-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='章番号 (1-8)', unique=True)),
                ('title', models.CharField(help_text='章タイトル (例: 第1章: Pythonの第一歩とデータ型)', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text='サブタイトル', max_length=255)),
                ('icon', models.CharField(default='book', help_text='アイコン名', max_length=50)),
                ('category', models.CharField(default='basic', max_length=50)),
                ('target_level', models.IntegerField(default=1, help_text='対象レベル (1-4)')),
                ('summary', models.TextField(blank=True, default='', help_text='章の概要・到達目標')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, help_text='レッスン順序')),
                ('title', models.CharField(help_text='単元タイトル (例: 1.1 変数宣言と数値演算)', max_length=200)),
                ('reading_time_minutes', models.IntegerField(default=5, help_text='読了目安時間(分)')),
                ('content_html', models.TextField(help_text='HTML形式のリッチ解説コンテンツ')),
                ('key_takeaways', models.JSONField(default=list, help_text='重要ポイント箇条書きリスト')),
                ('example_code', models.TextField(blank=True, default='', help_text='実行可能なサンプルコード')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter')),
            ],
            options={
                'ordering': ['chapter__order', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='演習課題タイトル', max_length=200)),
                ('description', models.TextField(help_text='HTML形式の課題指示文')),
                ('template', models.TextField(help_text='初期スターターコード')),
                ('test_cases', models.JSONField(default=list, help_text='テストケース配列')),
                ('setup_code', models.TextField(blank=True, default='', help_text='テスト前準備コード')),
                ('solution_code', models.TextField(blank=True, default='', help_text='模範解答コード')),
                ('explanation', models.TextField(blank=True, default='', help_text='解答の解説')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='curriculum.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(default='anonymous', max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_skipped_by_assessment', models.BooleanField(default=False, help_text='実力診断で習得済み判定されたか')),
                ('exercise_passed', models.BooleanField(default=False)),
                ('saved_code', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
            ],
            options={
                'unique_together': {('user_identifier', 'lesson')},
            },
        ),
    ]
